# Generated by Django 3.2.20 on 2024-03-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
