# Generated by Django 5.0.3 on 2024-03-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='remaning',
        ),
    ]
