# Generated by Django 4.2.11 on 2024-03-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_birthdate_customuser_country_and_more'),
        ('projects', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRating',
            new_name='Rating',
        ),
    ]
